### ISSUE TITLE
wrong patch url

### ISSUE THREAD

**Issue by Wireless4024** [ptr1337/linux-cacule#1]
running `yay -S linux-xanmod-cacule-rt linux-xanmod-cacule-rt-headers` giving error
```
==> ERROR: Failure while downloading https://raw.githubusercontent.com/ptr1337/kernel-patches/main/5.11/cacule-patches/cacule-5.11-rt.patch
```

https://github.com/ptr1337/linux-cacule-aur/blob/85b002ea1cf81f9449533f584b7ed135c8962c5d/linux-xanmod-cacule-rt/PKGBUILD#L75

is it a private repo?

**Comment by ptr1337** [comment]
Thanks for info! I updated the patches! i will update the aur build! 
Im reinstallingg my working rig right now. Could take until this evening i think.

If you want i have the kernel prebuilt on my fileserver, its the exact same version. 
@Wireless4024

Take a watch https://ptr1337.dev

Their you will find some prebuilt kernels from me! I will update the last kernels today. We have got many changes the last days.

**Comment by ptr1337** [comment]
> running `yay -S linux-xanmod-cacule-rt linux-xanmod-cacule-rt-headers` giving error
> 
> ```
> ==> ERROR: Failure while downloading https://raw.githubusercontent.com/ptr1337/kernel-patches/main/5.11/cacule-patches/cacule-5.11-rt.patch
> ```
> 
> https://github.com/ptr1337/linux-cacule-aur/blob/85b002ea1cf81f9449533f584b7ed135c8962c5d/linux-xanmod-cacule-rt/PKGBUILD#L75
> 
> is it a private repo?

Updated the aur package and all checksums. Should be running now! 

regards.
