### ISSUE TITLE
Possiblitiy to maintain the linux-cacule-lts package in cachyos repo?

### ISSUE THREAD

**Issue by Gontier-Julien** [ptr1337/linux-cacule#15]
Hi ptr1337!

First thank you so much for maintaining all of the linux cacule packages ^^
But i have i question, is there a possibility to have the linux-cacule-lts package maintained and precompiled in the cachyos repo? It would be really awesome ^^
They're is no obligation to do it of course, i've just wanted to know if that would be possible, i know it a lot of work to maintain all of those package ^^

**Comment by ptr1337** [comment]
Yeah, of course. Do you need 5.4 or 5.10 or both ? 

If you want you can also register at our forum and request packages. Soon we are gonna release our OS:) 

https://forum.cachyos.org 


Regards.

**Comment by Gontier-Julien** [comment]
I'll would need the 5.10 Lts kernel, and i think it is the kernel that most people use anyway in the Lts branch ^^
And thank you very much, really appreciate ^^

**Comment by ptr1337** [comment]
Should be up in some minutes.

**Comment by ptr1337** [comment]
Hey @Gontier-Julien 

Sorry it did failed many times cause some patches and dont got it to work. 
I will figure it out. 
Sorry.

**Comment by Gontier-Julien** [comment]
Yeah sure no problem ^^
Take the time needed to fix it, no need to apologize ^^

**Comment by ptr1337** [comment]
fixed with latest commit. gonna push tomorrow into the repo

regards:)

**Comment by Gontier-Julien** [comment]
Thank you very much! Really appreciate ^^

**Comment by Gontier-Julien** [comment]
Just a question because it seems really weird for me, is the size of the kernel normal??
It seems like there no compression on it

>Package (2)                          New Version  **Net Change**  Download Size
>
>cachyos-v3/linux-cacule-lts          5.10.70-1    **943.57 MiB**     942.80 MiB
>cachyos-v3/linux-cacule-lts-headers  5.10.70-1    **740.99 MiB**     182.17 MiB

Compared to the non-lts kernel:

>Package (2)                      New Version  **Net Change**  Download Size
>
>cachyos-v3/linux-cacule          5.14.9-3      **78.75 MiB**      37.31 MiB
>cachyos-v3/linux-cacule-headers  5.14.9-3     **130.29 MiB**      29.97 MiB

**Comment by ptr1337** [comment]
what the hell... moment

**Comment by ptr1337** [comment]
> Just a question because it seems really weird for me, is the size of the kernel normal?? It seems like there no compression on it
> 
> > Package (2)                          New Version  **Net Change**  Download Size
> > cachyos-v3/linux-cacule-lts          5.10.70-1    **943.57 MiB**     942.80 MiB
> > cachyos-v3/linux-cacule-lts-headers  5.10.70-1    **740.99 MiB**     182.17 MiB
> 
> Compared to the non-lts kernel:
> 
> > Package (2)                      New Version  **Net Change**  Download Size
> > cachyos-v3/linux-cacule          5.14.9-3      **78.75 MiB**      37.31 MiB
> > cachyos-v3/linux-cacule-headers  5.14.9-3     **130.29 MiB**      29.97 MiB

Going to rebase now somehow the kernel. Ill let you know if it works.

**Comment by ptr1337** [comment]
@Gontier-Julien 

Got it worked. 

It will be then in this repo:

https://github.com/CachyOS/linux-cachyos

Since i got a CI which automaticly builds the kernel when i update them!

Do you need also LTO or is GCC enough ?

Gonna push later!

**Comment by Gontier-Julien** [comment]
Gcc is enough don't worry ^^
Thank you so much for your hard work ^^
Just a little question what is the difference between `Cacule` and the `Baby` scheduler? And i've seen that the kernel is compressed with zstd `Ultra`, is this because of packages size or speed? Because i don't remember where exactly but iv'e read that the ultra in zstd is faster for some reason? (i promise i'm going to stop bothering you haha ^^)
And you can build ArchLinux package with github? I didn't know that was possible :D

**Comment by ptr1337** [comment]
Hey @Gontier-Julien 

Feel free to write me in telegram or discord. Easier to write all questions! 

Telegram: "@ptr1337"

Discord: https://discord.gg/xkserK7e

There you will find me! 

The LTS Kernel is in the -v3 repo!
