### ISSUE TITLE
PGO Patch MD5 missing in linux-cacule-rdb

### ISSUE THREAD

**Issue by Aarrayy** [ptr1337/linux-cacule#16]
Hey ptr again, hope you have a good day, i noticed after trying to install the new version of linux-cacule-rdb and enabling FULL-LTO + PGO that it fails after its checking md5sums of the patches, it seems like PGO patch md5 is missing in the PKGBUIILD, after putting it in the file, it builds normally

Again thanks for maintaining this repo <3

**Comment by ptr1337** [comment]
Yeah, i add the Checksum. If you got problems at the usage of it just hit me up.

I gonna probally switch soon with to this repo: 

https://github.com/CachyOS/linux-cachyos

Its better to provide for the OS more kernels then Cacule :)

**Comment by Aarrayy** [comment]
ohh thats nice, thanks for letting me know

**Comment by ptr1337** [comment]
> ohh thats nice, thanks for letting me know

At the moment cause PGO it seems like failing for me. 
I tried more then 15 tries. I'll get all time the profile but after trying it to merge it is failing. 

Gonna test it with 5.15-rc6 when its released if it works.
