### ISSUE TITLE
Several patches did not pass the validity check

### ISSUE THREAD

**Issue by MrWissenschaft** [ptr1337/linux-cacule#18]
Hello there!

Love your kernel, easy to use, customize and install!

Just noticed the below however when attempting to build just so you know :)

Hope you're having a very merry christmas!

==> Validating source files with md5sums...
    linux-5.15.11.tar.xz ... Passed
    config ... Passed
    cacule-5.15-full.patch ... Passed
    0001-arch-patches.patch ... FAILED
    0001-cfi.patch ... Passed
    0001-lru-patches.patch ... Passed
    0001-amdpstate.patch ... FAILED
    amd-sched.patch ... Passed
    0001-amd64-patches.patch ... Passed
    0001-bbr2.patch ... Passed
    0001-block-patches.patch ... Passed
    0001-cpu-patches.patch ... Passed
    0001-misc.patch ... Passed
    0001-btrfs-patches.patch ... FAILED
    0001-clearlinux-patches.patch ... Passed
    0001-intel-patches.patch ... Passed
    0001-ntfs3.patch ... Passed
    0001-ck-hrtimer.patch ... Passed
    0001-fixes-miscellaneous.patch ... Passed
    0001-futex-wait.v-fsync-winesync.patch ... Passed
    0001-hwmon-patches.patch ... Passed
    0001-ksmbd-patches.patch ... FAILED
    0001-pf-patches.patch ... Passed
    0001-page-table-check.patch ... FAILED
    0001-lqx-patches.patch ... Passed
    0001-lrng-patches.patch ... Passed
    0001-v4l2loopback.patch ... Passed
    0001-security-patches.patch ... Passed
    0001-spectre-patches.patch ... Passed
    0001-sbitmap-patches.patch ... Passed
    0001-xanmod-patches.patch ... Passed
    0001-net-patches.patch ... Passed
    0001-zstd.patch ... FAILED
    auto-cpu-optimization.sh ... Passed
==> ERROR: One or more files did not pass the validity check!

**Comment by ptr1337** [comment]
Hey @MrWissenschaft , 

Thanks for reporting, yes ive updated some patches and im on it to push them with their updated checksums into the aur.
You can still build them with passing the checkums, with the command --skipchecksums.

Here is the more maintained repo:

https://github.com/CachyOS/linux-cachyos

regards.

**Comment by ptr1337** [comment]
> Hello there!
> 
> Love your kernel, easy to use, customize and install!
> 
> Just noticed the below however when attempting to build just so you know :)
> 
> Hope you're having a very merry christmas!
> 
> ==> Validating source files with md5sums... linux-5.15.11.tar.xz ... Passed config ... Passed cacule-5.15-full.patch ... Passed 0001-arch-patches.patch ... FAILED 0001-cfi.patch ... Passed 0001-lru-patches.patch ... Passed 0001-amdpstate.patch ... FAILED amd-sched.patch ... Passed 0001-amd64-patches.patch ... Passed 0001-bbr2.patch ... Passed 0001-block-patches.patch ... Passed 0001-cpu-patches.patch ... Passed 0001-misc.patch ... Passed 0001-btrfs-patches.patch ... FAILED 0001-clearlinux-patches.patch ... Passed 0001-intel-patches.patch ... Passed 0001-ntfs3.patch ... Passed 0001-ck-hrtimer.patch ... Passed 0001-fixes-miscellaneous.patch ... Passed 0001-futex-wait.v-fsync-winesync.patch ... Passed 0001-hwmon-patches.patch ... Passed 0001-ksmbd-patches.patch ... FAILED 0001-pf-patches.patch ... Passed 0001-page-table-check.patch ... FAILED 0001-lqx-patches.patch ... Passed 0001-lrng-patches.patch ... Passed 0001-v4l2loopback.patch ... Passed 0001-security-patches.patch ... Passed 0001-spectre-patches.patch ... Passed 0001-sbitmap-patches.patch ... Passed 0001-xanmod-patches.patch ... Passed 0001-net-patches.patch ... Passed 0001-zstd.patch ... FAILED auto-cpu-optimization.sh ... Passed ==> ERROR: One or more files did not pass the validity check!

Should be sloved in the other repo. Got right now less time for the aur
