### ISSUE TITLE
Error while compiling kernel

### ISSUE THREAD

**Issue by Aarrayy** [ptr1337/linux-cacule#4]
Hey ptr, thanks for making this kernel with the cacule scheduler, i was trying to compile your new cacule-rdb-autogroup and i encountered this error after a minute in the process, hopefully this screenshot helps you figure out what the issue is

![image](https://user-images.githubusercontent.com/68795737/128202807-23bca7e6-9552-4ffd-a78b-fb06d69c824b.png)

**Comment by ptr1337** [comment]
Which kernel correctly ? 

Ill check in some minutes when i update to the new kernel. )

**Comment by Aarrayy** [comment]
> Which kernel correctly ?
> 
> Ill check in some minutes when i update to the new kernel. )

cacule-rdb-autogroup branch, didnt test the other ones

**Comment by ptr1337** [comment]
Ill update the next hour all kernels + patches.

**Comment by Aarrayy** [comment]
it works now.  thanks for the fix
