### ISSUE TITLE
About rdb patch and cacule-rdb-autogroup patch removed from PKGBUILD

### ISSUE THREAD

**Issue by RiverOnVenus** [ptr1337/linux-cacule#5]
Hi, ptr1337, thanks for your contribution, these kernels are great. I noticed that in the corresponding PKGBUILD you seem to have removed the rdb patch and the cacule-rdb-autogroup patch.

**Comment by ptr1337** [comment]
Hey dude, 

Every patch is now in one patch which is Cacule Revisionv3. 
Only the CONFIG values are needed for the  working kernel u want

**Comment by RiverOnVenus** [comment]
I see, thk
