### ISSUE TITLE
Error when using cachyos-repo

### ISSUE THREAD

**Issue by RiverOnVenus** [ptr1337/linux-cacule#7]
Hi, I run the script(`sudo ./cachyos-repo.sh`) according to the README and everything worked fine during the process.

The script echo "x86-64-v3 is supported".

But when I install the kernel there is an error (error: failed to prepare transaction (package architecture is not valid)

![image](https://user-images.githubusercontent.com/79885139/130351558-adcd22a2-05bc-4e04-96cf-2b575b093e3d.png)

![image](https://user-images.githubusercontent.com/79885139/130351578-0e088cc8-db1f-436a-b0c8-03aa9081bbaf.png)

OS: Arch Linux x86_64

**Comment by ptr1337** [comment]
> Hi, I run the script(`sudo ./cachyos-repo.sh`) according to the README and everything worked fine during the process.
> 
> The script echo "x86-64-v3 is supported".
> 
> But when I install the kernel there is an error (error: failed to prepare transaction (package architecture is not valid)
> 
> ![image](https://user-images.githubusercontent.com/79885139/130351558-adcd22a2-05bc-4e04-96cf-2b575b093e3d.png)
> 
> ![image](https://user-images.githubusercontent.com/79885139/130351578-0e088cc8-db1f-436a-b0c8-03aa9081bbaf.png)
> 
> OS: Arch Linux x86_64

Hey, I'm sorry for the late answer. I don't know why it didn't updated successfully, I did several test (but also updated the script some days ago). 

Take a watch at your pacman.conf:

sudo nano /etc/pacman.conf

Checkout for following line:
Architecture = Auto 

and change it into 

Architecture = x86_64 x86_64_v3 

Should be running then completely. If you get any issues, feel free to reply. 

Regards

**Comment by RiverOnVenus** [comment]
> > Hi, I run the script(`sudo ./cachyos-repo.sh`) according to the README and everything worked fine during the process.
> > The script echo "x86-64-v3 is supported".
> > But when I install the kernel there is an error (error: failed to prepare transaction (package architecture is not valid)
> > ![image](https://user-images.githubusercontent.com/79885139/130351558-adcd22a2-05bc-4e04-96cf-2b575b093e3d.png)
> > ![image](https://user-images.githubusercontent.com/79885139/130351578-0e088cc8-db1f-436a-b0c8-03aa9081bbaf.png)
> > OS: Arch Linux x86_64
> 
> Hey, I'm sorry for the late answer. I don't know why it didn't updated successfully, I did several test (but also updated the script some days ago).
> 
> Take a watch at your pacman.conf:
> 
> sudo nano /etc/pacman.conf
> 
> Checkout for following line:
> Architecture = Auto
> 
> and change it into
> 
> Architecture = x86_64 x86_64_v3
> 
> Should be running then completely. If you get any issues, feel free to reply.
> 
> Regards

Change Architecture = Auto into

Architecture = x86_64 x86_64_v3

It can be updated and installed normally now

Hope you have a good day! : )

Thanks and Regards
