### ISSUE TITLE
Error downloading patches, url not found Cacule LLVM

### ISSUE THREAD

**Issue by Lukas0120** [ptr1337/linux-cacule#8]
Tried building a Cacule llvm kernel but got an error when downloading patches saying url not found. Think there is just a mistake on the url

**Comment by ptr1337** [comment]
Will be fixed, there are many patched got updated and ill add them and test it.

30 Min everything should be fine. But thanks for your report!

**Comment by Lukas0120** [comment]
Problem fixed now but getting a md5 integrity check error now. Differ in size.

Thanks for the quick reply and all the amazing work!

**Comment by ptr1337** [comment]
> Problem fixed now but getting a md5 integrity check error now. Differ in size.
> 
> Thanks for the quick reply and all the amazing work!

Please wait some minutes, then everything will run perfectly! :)

**Comment by ptr1337** [comment]
@Lukas0120 

Pull now from the repo, it should everthing sloved! 
Close the issue if everything is okay

regards

**Comment by Lukas0120** [comment]
Everything worked now and was able to build the kernel with lto but when booting it gets stuck at clean files. 

When building I got a dkms nvidia error and logs when booting says

nvidiafb cannot request pci regions

So I assume it's nvidia driver problem? Sorry for all the questions, really appreciate your help

**Comment by ptr1337** [comment]
Oh, ill rework the README. for using LTO Kernels on Nvidia.  its failing due there dkms. 

Ill update the readme fast. 

Btw: I also provide prebuilt kernels.

**Comment by Lukas0120** [comment]
Ah okey I see the problem then :)

Wanted to try and compile my own kernel first before I look into prebuilt.

But the prebuilt ones are available from your repo or Cachyos right?

**Comment by ptr1337** [comment]
Nope, that's not the problem. 

I have updated the README check this out under Nvidia, this will solve your problem. 

Report back if everything went fine!

**Comment by Lukas0120** [comment]
Sorry for the late reply, worked perfectly this time, thanks for all the help and your awesome work!
